[package]
name = "afrxo/glue"
description = "Another game framework."
version = "6.1.9"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["Packages"]

[dependencies]
Promise = "evaera/promise@4.0.0"